framework:
    workflows:
      reservation:
        type: "workflow"
        marking_store:
          type: "single_state"
          arguments:
            - "state"
        supports:
          - App\Entity\Reservation
        places:
          - created
          - accepted
          - refused
          - cancelled
          - cancelled_ok
        transitions:
          # Validation de la demande pour la secretaire
          demand_validation:
            from: created
            to: accepted
          # Rejet de la demande par la secretaire
          demand_refused:
            from: created
            to: refused
          # Annulation de l'utilisateur qui a créer la demande car il s'est trompé
          cancel_demand:
            from: created
            to: cancelled
          cancel_after:
            from: accepted
            to: cancelled
          cancel_booking:
            from: cancelled
            to: cancelled_ok
