version: "3"
services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./.db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  php:
    build: Docker
    image: webforce/php:7.2-fpm
    ports:
      - "81:81"
    volumes:
      - .:/var/www/lava
    command: php -S 0.0.0.0:81 -t /var/www/lava/public
  nginx:
    image: nginx
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/local.dev.conf
      - .:/var/www/laval
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80